### ISSUE TITLE
Which USB Port on RP4?

### ISSUE THREAD

**Issue by rdmueller** [likeablob/rpi-wfh-webcam#6]
Great Project - thanx for sharing!

Quick question - which is the right USB port on the Raspberry Pi 4? Is it the USB-C-Type through which you also power the device?

**Comment by likeablob** [comment]
Hi! @rdmueller Hope you enjoy this project. :wave:   
Yes, it is. You can (and have to) use a Type-C to Type-C cable for powering and gadget-USB communicating. 
May be you can enable the g_multiple and g_serial modules for easy serial console access, but currently I ended up with the usual SSH setup.

**Comment by rdmueller** [comment]
thanx!
